### ISSUE TITLE
[BUG] File Manager not working on 0.4.11

### ISSUE THREAD

**Issue by Oshcakes** [averrin/alpha-suit#11]
**Module Version:** 0.4.11

**Describe the bug**
The File Manager will no longer launch. Rolling back to 0.4.10 resolves the issue. I have tried on local foundry as well as the forge in new and existing worlds.

**To Reproduce**
Click File Manager button or view error in console on world launch.

**Screenshots**
![image](https://user-images.githubusercontent.com/61471647/202337108-a3301edb-b6ad-42b8-9f6a-f27919fa7bc1.png)

**Browser:**
Chrome or native foundry app

**Foundry Version:** 
v10 288 and 290

**Game System:** 
dnd5e

**Comment by buttonpushertv** [comment]
I also see this error when trying to manually rebuild the index on v.4.11

![image](https://user-images.githubusercontent.com/24526709/202344579-e5938686-de64-46e4-b31b-3a40296a8941.png)

**Comment by buttonpushertv** [comment]
Additionally, the index seems to get reset on every page refresh, but the `index.js` file doesn't get erased from the file system, so it's there just not being read? Which may trigger the first error?

**Comment by averrin** [comment]
Thanks for your report, I'll investigate it in a several hours.
But:
* the second error have no impact at all (but will be fixed of course)
* you mixed "file index" term and file "index.js". It's a coincidence that both have "index" :) The file index saves between page refreshes only in "stored index" mode. Otherwise it keeps in memory and rebuilds every launch (to be actual).

But as I say, I'm not sure that everything works fine and will release new version with fixes today

**Comment by averrin** [comment]
I made a "hot"fix: https://github.com/averrin/alpha-suit/releases/tag/0.4.12
I hope it helps. If not, feel free to reopen this issue.
